title: Distributed Computing 4 Kids (and Executives)
description: Making distributed computing fun, accessible, and exciting for kids and curious minds everywhere!
subscribe_url: https://docs.google.com/forms/d/e/1FAIpQLSd_91ATGTGkrr_ip6GoVVigmYjj7UqjCabOdA1Lt_F7rtv1jQ/viewform?usp=publish-editor
baseurl: ""
url: ""

# Launch date
launch_date: "July 2026"

# Build settings
markdown: kramdown
theme: null
plugins: []

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor/
